{% set name = "asapdiscovery" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/choderalab/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 5f4cb2e0f01823459ee5dd2f7b9f94b3dfa259dfc42b03bbc0146ef9b7e8988a

build:
  skip: true  # [py>311]
  skip: true  # [py<310]
  skip: true  # [win]
  number: 0


requirements:

  host:
    - python
    - pip
    - versioningit

  run:
    - python

    # data
    - requests
    - boto3
    - moto
    - flask
    - flask-cors
    - typing-extensions
    - biopython
    - ase
    - validators
    - pyyaml
    - sigfig
    - multimethod
    - rdkit
    - appdirs
    - mdanalysis
    - openff-toolkit
    - pandas
    - pydantic >=1.10.8,<2.0.0a0
    - semver

    # ml
    - pytorch
    - pytorch_geometric >=2.5.0
    - pytorch_cluster
    - pytorch_scatter
    - pytorch_sparse
    - numpy
    - h5py
    - e3nn
    - dgl
    - dgllife
    - pooch
    - mtenn >=0.5.1
    - wandb

    # md
    - openmm
    - openmmforcefields
    - mdtraj
    - openff-toolkit
    - cudatoolkit  # [not osx]

    # execution
    - distributed
    - dask
    - dask-jobqueue
    - dask-cuda  # [not osx]
    - netifaces

    # viz
    - imageio
    - pymol-open-source
    - gifsicle
    - plip
    - plotly
    - pygifsicle
    - airium
    - logomaker

    # simulation
    - openfe =>0.14.0
    - gufe =>0.9.5
    - httpx
    - perses >=0.10.2
    - kartograf
    - rich
    - alchemiscale-client
    - cinnabar >=0.4.1 

    # testing
    - pytest
    - pytest-cov
    - pytest-xdist
    - codecov
    - pytest-console-scripts
    - pytest-timeout
    - requests-mock
    - mock

    # cli
    - click

test:
  imports:
    - asapdiscovery
    - asapdiscovery.alchemy
    - asapdiscovery.cli
    - asapdiscovery.data
    - asapdiscovery.dataviz
    - asapdiscovery.genetics
    - asapdiscovery.ml
    - asapdiscovery.modeling
    - asapdiscovery.simulation
    - asapdiscovery.workflows


about:
  home: https://github.com/choderalab/asapdiscovery
  summary: 'A toolkit for structure-based open antiviral drug discovery by the ASAP Discovery Consortium'
  description: |
    A toolkit for structure-based open antiviral drug discovery by the ASAP Discovery Consortium
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://asapdiscovery.readthedocs.io/
  dev_url: https://github.com/choderalab/asapdiscovery

extra:
  recipe-maintainers:
    - hmacdope
    - jthorton
    - JenkeScheen
    - mikemhenry
    - ijpulidos
    - kaminow
    - apayne97
